### ISSUE TITLE
Create library

### ISSUE THREAD

**Issue by rolaveric** [rolaveric/angular-falcor#6]
Approaching a point where the code may be reusable in other projects.
Should wrap the reusable code into library and move the example code into an 'example/' folder.

**Comment by greim** [comment]
+1

I've been looking into this and would also be interested in a library!

**Comment by rolaveric** [comment]
Cool!
I'll try to set aside some time this weekend to wrap it up as a library.
I'll also have to think about how to make it ES5 friendly without losing all it's ES6 shine.

**Comment by greim** [comment]
I'd be happy to contribute if needed. I've published a few libs to npm with automatic transpiling from es6 => es5. I'm looking at integrating Falcor into a pretty sizeable Angular 1.x project.

**Comment by rolaveric** [comment]
In that case, did you want to create and publish a library yourself?
I'm not using Falcor outside of hobby projects right now, and it makes a lot more sense for it to be managed by someone who's actively using it.
I'd be happy to assist where I can, and the code here is under MIT license so you're free to use what you want.

**Comment by greim** [comment]
I'll consider it. I'm still learning Angular so I don't want to publish something until I feel like I have a better grip on how it works.

**Comment by greim** [comment]
I published a lib, but ended up using a slightly different approach. https://github.com/greim/ng-falcor

Still pretty beta, but if you get a change to take a look at it I'd love any feedback.

**Comment by rolaveric** [comment]
I like your approach - very slick API!
